"""
Validation Schema — Stage 4 output.

Defines the structured output for the Validation Engine.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class ValidationSeverity(str, Enum):
    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


class ValidationLayer(str, Enum):
    """Which layer the validation error belongs to."""
    UI = "ui"
    API = "api"
    DB = "db"
    AUTH = "auth"
    CROSS_LAYER = "cross_layer"
    INTENT = "intent"
    DESIGN = "design"


class ValidationErrorDetail(BaseModel):
    """A single validation error."""
    id: str = Field(..., description="Unique error identifier")
    layer: ValidationLayer
    severity: ValidationSeverity = Field(default=ValidationSeverity.ERROR)
    field: str = Field(default="", description="Field path that failed validation")
    message: str = Field(..., description="Human-readable error description")
    expected: str = Field(default="", description="What was expected")
    actual: str = Field(default="", description="What was found")
    fix_suggestion: str = Field(default="", description="Suggested fix")
    auto_fixable: bool = Field(
        default=False,
        description="Whether the repair engine can fix this automatically",
    )


class ValidationResult(BaseModel):
    """
    Stage 4 Output: Complete validation result.

    Status is PASS only if there are zero errors (warnings are allowed).
    """
    status: str = Field(
        ...,
        description="PASS or FAIL",
        pattern=r"^(PASS|FAIL)$",
    )
    errors: list[ValidationErrorDetail] = Field(default_factory=list)
    warnings: list[ValidationErrorDetail] = Field(default_factory=list)
    total_checks: int = Field(default=0)
    passed_checks: int = Field(default=0)
    failed_checks: int = Field(default=0)

    @property
    def error_count(self) -> int:
        return len(self.errors)

    @property
    def warning_count(self) -> int:
        return len(self.warnings)

    def has_errors_in_layer(self, layer: ValidationLayer) -> bool:
        return any(e.layer == layer for e in self.errors)

    def errors_in_layer(self, layer: ValidationLayer) -> list[ValidationErrorDetail]:
        return [e for e in self.errors if e.layer == layer]

    def auto_fixable_errors(self) -> list[ValidationErrorDetail]:
        return [e for e in self.errors if e.auto_fixable]


class RepairReport(BaseModel):
    """Report generated by the Repair Engine after fixing issues."""
    iteration: int = Field(..., ge=1)
    layer: ValidationLayer
    errors_fixed: list[str] = Field(default_factory=list, description="Error IDs that were fixed")
    errors_remaining: list[str] = Field(default_factory=list, description="Error IDs that remain")
    changes_made: list[str] = Field(default_factory=list, description="Description of changes")
    success: bool = Field(default=False)
